//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 08:50:35 AM COT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://API.co/DocRegistroActivo")
package co.api.docregistroactivo;
