//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 01:33:14 PM COT 
//


package co.api.docrespuestaactivo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for areasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="areasType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="nombreArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ciudadArea" type="{http://API.co/DocRespuestaActivo}ciudadesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "areasType", propOrder = {
    "idArea",
    "nombreArea",
    "ciudadArea"
})
public class AreasType {

    @XmlElement(required = true)
    protected String idArea;
    @XmlElement(required = true)
    protected String nombreArea;
    @XmlElement(required = true)
    protected CiudadesType ciudadArea;

    /**
     * Gets the value of the idArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdArea() {
        return idArea;
    }

    /**
     * Sets the value of the idArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdArea(String value) {
        this.idArea = value;
    }

    /**
     * Gets the value of the nombreArea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombreArea() {
        return nombreArea;
    }

    /**
     * Sets the value of the nombreArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombreArea(String value) {
        this.nombreArea = value;
    }

    /**
     * Gets the value of the ciudadArea property.
     * 
     * @return
     *     possible object is
     *     {@link CiudadesType }
     *     
     */
    public CiudadesType getCiudadArea() {
        return ciudadArea;
    }

    /**
     * Sets the value of the ciudadArea property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiudadesType }
     *     
     */
    public void setCiudadArea(CiudadesType value) {
        this.ciudadArea = value;
    }

}
