//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 01:34:25 PM COT 
//


package co.api.docrespuestaactivo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for DocumentoModificarActivoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DocumentoModificarActivoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="serialActual" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaBajaActual" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="serialNuevo" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="fechaBajaNueva" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DocumentoModificarActivoType", propOrder = {
    "serialActual",
    "fechaBajaActual",
    "serialNuevo",
    "fechaBajaNueva"
})
public class DocumentoModificarActivoType {

    protected String serialActual;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaBajaActual;
    protected String serialNuevo;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaBajaNueva;

    /**
     * Gets the value of the serialActual property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialActual() {
        return serialActual;
    }

    /**
     * Sets the value of the serialActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialActual(String value) {
        this.serialActual = value;
    }

    /**
     * Gets the value of the fechaBajaActual property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaBajaActual() {
        return fechaBajaActual;
    }

    /**
     * Sets the value of the fechaBajaActual property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaBajaActual(XMLGregorianCalendar value) {
        this.fechaBajaActual = value;
    }

    /**
     * Gets the value of the serialNuevo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNuevo() {
        return serialNuevo;
    }

    /**
     * Sets the value of the serialNuevo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNuevo(String value) {
        this.serialNuevo = value;
    }

    /**
     * Gets the value of the fechaBajaNueva property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaBajaNueva() {
        return fechaBajaNueva;
    }

    /**
     * Sets the value of the fechaBajaNueva property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaBajaNueva(XMLGregorianCalendar value) {
        this.fechaBajaNueva = value;
    }

}
