//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 08:50:35 AM COT 
//


package co.api.docrespuestaactivo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for personasType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="personasType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idPersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fechaNaciPersona" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="nombrePersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="apellidoPersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="direccionPersona" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ciudadPersona" type="{http://API.co/DocRespuestaActivo}ciudadesType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "personasType", propOrder = {
    "idPersona",
    "fechaNaciPersona",
    "nombrePersona",
    "apellidoPersona",
    "direccionPersona",
    "ciudadPersona"
})
public class PersonasType {

    @XmlElement(required = true)
    protected String idPersona;
    @XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar fechaNaciPersona;
    @XmlElement(required = true)
    protected String nombrePersona;
    @XmlElement(required = true)
    protected String apellidoPersona;
    @XmlElement(required = true)
    protected String direccionPersona;
    @XmlElement(required = true)
    protected CiudadesType ciudadPersona;

    /**
     * Gets the value of the idPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdPersona() {
        return idPersona;
    }

    /**
     * Sets the value of the idPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdPersona(String value) {
        this.idPersona = value;
    }

    /**
     * Gets the value of the fechaNaciPersona property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFechaNaciPersona() {
        return fechaNaciPersona;
    }

    /**
     * Sets the value of the fechaNaciPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFechaNaciPersona(XMLGregorianCalendar value) {
        this.fechaNaciPersona = value;
    }

    /**
     * Gets the value of the nombrePersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNombrePersona() {
        return nombrePersona;
    }

    /**
     * Sets the value of the nombrePersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNombrePersona(String value) {
        this.nombrePersona = value;
    }

    /**
     * Gets the value of the apellidoPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApellidoPersona() {
        return apellidoPersona;
    }

    /**
     * Sets the value of the apellidoPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApellidoPersona(String value) {
        this.apellidoPersona = value;
    }

    /**
     * Gets the value of the direccionPersona property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDireccionPersona() {
        return direccionPersona;
    }

    /**
     * Sets the value of the direccionPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDireccionPersona(String value) {
        this.direccionPersona = value;
    }

    /**
     * Gets the value of the ciudadPersona property.
     * 
     * @return
     *     possible object is
     *     {@link CiudadesType }
     *     
     */
    public CiudadesType getCiudadPersona() {
        return ciudadPersona;
    }

    /**
     * Sets the value of the ciudadPersona property.
     * 
     * @param value
     *     allowed object is
     *     {@link CiudadesType }
     *     
     */
    public void setCiudadPersona(CiudadesType value) {
        this.ciudadPersona = value;
    }

}
