//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 08:50:35 AM COT 
//


package co.api.docrespuestaactivo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespBuscarTodosActivosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespBuscarTodosActivosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="descripcionPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="activosFijos" type="{http://API.co/DocRespuestaActivo}activosFijosType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespBuscarTodosActivosType", propOrder = {
    "codigoPeticion",
    "descripcionPeticion",
    "activosFijos"
})
public class RespBuscarTodosActivosType {

    @XmlElement(required = true)
    protected BigInteger codigoPeticion;
    @XmlElement(required = true)
    protected BigInteger descripcionPeticion;
    protected List<ActivosFijosType> activosFijos;

    /**
     * Gets the value of the codigoPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoPeticion() {
        return codigoPeticion;
    }

    /**
     * Sets the value of the codigoPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoPeticion(BigInteger value) {
        this.codigoPeticion = value;
    }

    /**
     * Gets the value of the descripcionPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDescripcionPeticion() {
        return descripcionPeticion;
    }

    /**
     * Sets the value of the descripcionPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDescripcionPeticion(BigInteger value) {
        this.descripcionPeticion = value;
    }

    /**
     * Gets the value of the activosFijos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the activosFijos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActivosFijos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActivosFijosType }
     * 
     * 
     */
    public List<ActivosFijosType> getActivosFijos() {
        if (activosFijos == null) {
            activosFijos = new ArrayList<ActivosFijosType>();
        }
        return this.activosFijos;
    }

}
