//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 08:50:35 AM COT 
//


package co.api.docrespuestaactivo;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespuestaNuevoActivoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespuestaNuevoActivoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="descripcionPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaNuevoActivoType", propOrder = {
    "codigoPeticion",
    "descripcionPeticion"
})
public class RespuestaNuevoActivoType {

    @XmlElement(required = true)
    protected BigInteger codigoPeticion;
    @XmlElement(required = true)
    protected BigInteger descripcionPeticion;

    /**
     * Gets the value of the codigoPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoPeticion() {
        return codigoPeticion;
    }

    /**
     * Sets the value of the codigoPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoPeticion(BigInteger value) {
        this.codigoPeticion = value;
    }

    /**
     * Gets the value of the descripcionPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDescripcionPeticion() {
        return descripcionPeticion;
    }

    /**
     * Sets the value of the descripcionPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDescripcionPeticion(BigInteger value) {
        this.descripcionPeticion = value;
    }

}
