//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.12 at 01:33:14 PM COT 
//


package co.api.docrespuestaactivo;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RespuestaListarDatosType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RespuestaListarDatosType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="descripcionPeticion" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="areas" type="{http://API.co/DocRespuestaActivo}areasType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="personas" type="{http://API.co/DocRespuestaActivo}personasType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RespuestaListarDatosType", propOrder = {
    "codigoPeticion",
    "descripcionPeticion",
    "areas",
    "personas"
})
public class RespuestaListarDatosType {

    @XmlElement(required = true)
    protected BigInteger codigoPeticion;
    @XmlElement(required = true)
    protected BigInteger descripcionPeticion;
    protected List<AreasType> areas;
    protected List<PersonasType> personas;

    /**
     * Gets the value of the codigoPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCodigoPeticion() {
        return codigoPeticion;
    }

    /**
     * Sets the value of the codigoPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCodigoPeticion(BigInteger value) {
        this.codigoPeticion = value;
    }

    /**
     * Gets the value of the descripcionPeticion property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDescripcionPeticion() {
        return descripcionPeticion;
    }

    /**
     * Sets the value of the descripcionPeticion property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDescripcionPeticion(BigInteger value) {
        this.descripcionPeticion = value;
    }

    /**
     * Gets the value of the areas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the areas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAreas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AreasType }
     * 
     * 
     */
    public List<AreasType> getAreas() {
        if (areas == null) {
            areas = new ArrayList<AreasType>();
        }
        return this.areas;
    }

    /**
     * Gets the value of the personas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the personas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPersonas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PersonasType }
     * 
     * 
     */
    public List<PersonasType> getPersonas() {
        if (personas == null) {
            personas = new ArrayList<PersonasType>();
        }
        return this.personas;
    }

}
